# Generated by Django 5.0.6 on 2024-11-08 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Rooms",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="编号"
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=22, verbose_name="名称"),
                ),
                ("number", models.IntegerField(default=0, verbose_name="座位数量")),
                (
                    "photo",
                    models.FileField(
                        default="", upload_to="Room/photo/", verbose_name="头像"
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("is_active", models.BooleanField(default=True, verbose_name="活跃状态")),
            ],
            options={
                "verbose_name_plural": "自习室管理",
                "db_table": "Room",
            },
        ),
        migrations.CreateModel(
            name="SignCode",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="编号"
                    ),
                ),
                ("text", models.TextField(default="", verbose_name="内容")),
                ("time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("is_active", models.BooleanField(default=True, verbose_name="活跃状态")),
            ],
            options={
                "verbose_name_plural": "签到码",
                "db_table": "sign_code",
            },
        ),
        migrations.CreateModel(
            name="Students",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="编号"
                    ),
                ),
                (
                    "name",
                    models.CharField(default="", max_length=22, verbose_name="姓名"),
                ),
                (
                    "password",
                    models.CharField(default="", max_length=32, verbose_name="密码"),
                ),
                (
                    "phone",
                    models.CharField(default="", max_length=11, verbose_name="手机号"),
                ),
                (
                    "email",
                    models.CharField(default="", max_length=22, verbose_name="邮箱"),
                ),
                ("time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "photo",
                    models.FileField(
                        default="", upload_to="Students/photo/", verbose_name="头像"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="活跃状态")),
            ],
            options={
                "verbose_name_plural": "学生管理",
                "db_table": "Students",
            },
        ),
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="编号"
                    ),
                ),
                (
                    "title",
                    models.CharField(default="", max_length=120, verbose_name="题目"),
                ),
                ("text", models.TextField(default="", verbose_name="内容")),
                ("time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("is_active", models.BooleanField(default=True, verbose_name="活跃状态")),
            ],
            options={
                "verbose_name_plural": "提示管理",
                "db_table": "Text",
            },
        ),
        migrations.CreateModel(
            name="Integrals",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="编号"
                    ),
                ),
                (
                    "title",
                    models.CharField(default="", max_length=220, verbose_name="警告题目"),
                ),
                (
                    "text",
                    models.TextField(default="", max_length=220, verbose_name="警告内容内容"),
                ),
                ("time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("is_active", models.BooleanField(default=True, verbose_name="活跃状态")),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="login.students",
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "扣积分管理",
                "db_table": "Integral",
            },
        ),
        migrations.CreateModel(
            name="Bookings",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="编号"
                    ),
                ),
                ("number", models.IntegerField(default=0, verbose_name="预约座位号")),
                (
                    "period",
                    models.IntegerField(
                        choices=[(1, "上午"), (2, "下午"), (3, "晚自习")],
                        default=1,
                        verbose_name="时间",
                    ),
                ),
                ("time", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                (
                    "is_active",
                    models.IntegerField(
                        choices=[(1, "预约"), (2, "已签到"), (3, "未签到"), (4, "已取消")],
                        default=1,
                        verbose_name="活跃状态",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="login.rooms",
                        verbose_name="自习室",
                    ),
                ),
                (
                    "students",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="login.students",
                        verbose_name="学生",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "预约管理",
                "db_table": "Booking",
            },
        ),
    ]
