# Generated by Django 5.2 on 2025-04-26 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='密码'),
        ),
    ]
