# Generated by Django 5.2 on 2025-04-26 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_students_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次登录'),
        ),
    ]
