# Generated by Django 5.1.7 on 2025-03-28 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundMusic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题')),
                ('audio_file', models.FileField(upload_to='music/', verbose_name='音频文件')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='上传时间')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.students', verbose_name='上传者')),
            ],
            options={
                'verbose_name': '背景音乐',
                'verbose_name_plural': '背景音乐',
                'ordering': ['-upload_time'],
            },
        ),
    ]
